name: recipe_sharing_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  firebase_storage: ^12.4.9
  like_button: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/heart1.png
    - assets/images/heart2.png
    - assets/images/user.png
    - assets/images/pizza.jpeg
