// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTa6rktKVqLF_EpTpp8XIRc6AseXDeo_A',
    appId: '1:290261785269:web:3bf4de696fb0d6cc05fcfc',
    messagingSenderId: '290261785269',
    projectId: 'test-9f11b',
    authDomain: 'test-9f11b.firebaseapp.com',
    storageBucket: 'test-9f11b.firebasestorage.app',
    measurementId: 'G-75VR2LHYF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBThfP9B85mLui8-tS9W-ujdpdR8naoV_Y',
    appId: '1:290261785269:android:28edddd9fa859d6b05fcfc',
    messagingSenderId: '290261785269',
    projectId: 'test-9f11b',
    storageBucket: 'test-9f11b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsqzgG4y2ltpO_T1s-2NM2wBjN_TJ_ZWQ',
    appId: '1:290261785269:ios:e5e98d3ea766ef4505fcfc',
    messagingSenderId: '290261785269',
    projectId: 'test-9f11b',
    storageBucket: 'test-9f11b.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsqzgG4y2ltpO_T1s-2NM2wBjN_TJ_ZWQ',
    appId: '1:290261785269:ios:e5e98d3ea766ef4505fcfc',
    messagingSenderId: '290261785269',
    projectId: 'test-9f11b',
    storageBucket: 'test-9f11b.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTa6rktKVqLF_EpTpp8XIRc6AseXDeo_A',
    appId: '1:290261785269:web:bab772e093329bf805fcfc',
    messagingSenderId: '290261785269',
    projectId: 'test-9f11b',
    authDomain: 'test-9f11b.firebaseapp.com',
    storageBucket: 'test-9f11b.firebasestorage.app',
    measurementId: 'G-CTPSP4Y48G',
  );
}
